-- Update student emails
UPDATE students SET email = 'gabriel.albrecht@stpaulclark.com' WHERE full_name = 'Gabriel Alexander Albrecht';
UPDATE students SET email = 'yxabella.aldana@stpaulclark.com' WHERE full_name = 'Yxabella Aldana';
UPDATE students SET email = 'soojeong.cho@stpaulclark.com' WHERE full_name = 'Soojeong Diaz Cho';
UPDATE students SET email = 'seokwoo.hong@stpaulclark.com' WHERE full_name = 'Seokwoo Hong';
UPDATE students SET email = 'woohyun@stpaulclark.com' WHERE full_name = 'Woohyun Ko';
UPDATE students SET email = 'seryn.kyung@stpaulclark.com' WHERE full_name = 'Seryn Kyung';
UPDATE students SET email = 'woojae.lee@stpaulclark.com' WHERE full_name = 'Woojae Lee';
UPDATE students SET email = 'quangbao.ma@stpaulclark.com' WHERE full_name = 'Quang Bao Ma';
UPDATE students SET email = 'vretchard.mateo@stpaulclark.com' WHERE full_name = 'Vhretchard Mateo';
UPDATE students SET email = 'sheenbee.oh@stpaulclark.com' WHERE full_name = 'Sheenbee Oh';
UPDATE students SET email = 'rahee.park@stpaulclark.com' WHERE full_name = 'Rahee Park';
UPDATE students SET email = 'sia.park@stpaulclark.com' WHERE full_name = 'Sia Park';
UPDATE students SET email = 'ayaan.verma@stpaulclark.com' WHERE full_name = 'Ayaan Verma';
UPDATE students SET email = 'myra@stpaulclark.com' WHERE full_name = 'Myra James Williams';
UPDATE students SET email = 'sua.an@stpaulclark.com' WHERE full_name = 'Sua An';
UPDATE students SET email = 'seowoo.chang@stpaulclark.com' WHERE full_name = 'Seowoo Chang';
UPDATE students SET email = 'jiung.choi@stpaulclark.com' WHERE full_name = 'Jiung Choi';
UPDATE students SET email = 'adi.chopra@stpaulclark.com' WHERE full_name = 'Adi Chopra';
UPDATE students SET email = 'macy.corpuz@stpaulclark.com' WHERE full_name = 'Macy Margaux Corpuz';
UPDATE students SET email = 'erika.dedil@stpaulclark.com' WHERE full_name = 'Erika Amor Dedil';
UPDATE students SET email = 'sanghyukg@stpaulclark.com' WHERE full_name = 'Sanghyuk Go';
UPDATE students SET email = 'sophia.headley@stpaulclark.com' WHERE full_name = 'Cataleyna Sophia Headley';
UPDATE students SET email = 'seokju.hong@stpaulclark.com' WHERE full_name = 'Seokju Hong';
UPDATE students SET email = 'kyuhyeon.kim@stpaulclark.com' WHERE full_name = 'Kyuhyeon Kim';
UPDATE students SET email = 'huije.kim@stpaulclark.com' WHERE full_name = 'Huije Kim';
UPDATE students SET email = 'suryn.kyung@stpaulclark.com' WHERE full_name = 'Suryn Kyung';
UPDATE students SET email = 'nayeongl@stpaulclark.com' WHERE full_name = 'Nayeong Lee';
UPDATE students SET email = 'jeongwon.lee@stpaulclark.com' WHERE full_name = 'Jeongwon Lee';
UPDATE students SET email = 'chrystelle.magat@stpaulclark.com' WHERE full_name = 'Chrystelle Magat';
UPDATE students SET email = 'jacob.leejun@stpaulclark.com' WHERE full_name = 'Jacob Leejun Park';
UPDATE students SET email = 'juwon.park@stpaulclark.com' WHERE full_name = 'Juwon Park';
UPDATE students SET email = 'eliana.saburdo@stpaulclark.com' WHERE full_name = 'Eliana Saburdo';
UPDATE students SET email = 'biya@stpaulclark.com' WHERE full_name = 'Biya Shin';
UPDATE students SET email = 'jiyeon.song@stpaulclark.com' WHERE full_name = 'Jiyeon Song';
UPDATE students SET email = 'camry.tobias@stpaulclark.com' WHERE full_name = 'Camry Tobias';
UPDATE students SET email = 'lian.tseng@stpaulclark.com' WHERE full_name = 'Li-An Tseng';
UPDATE students SET email = 'chi-wen.wang@stpaulclark.com' WHERE full_name = 'Chi-Wen Wang';
UPDATE students SET email = 'alliah.bonoyer@stpaulclark.com' WHERE full_name = 'Alliah Michelle Bonoyer';
UPDATE students SET email = 'irene.obregon@stpaulclark.com' WHERE full_name = 'Irene Caminero Obregon';
UPDATE students SET email = 'logan.corkery@stpaulclark.com' WHERE full_name = 'Logan Maurice Corkery';
UPDATE students SET email = 'yeonkyu.cho@stpaulclark.com' WHERE full_name = 'Yeonkyu Cho';
UPDATE students SET email = 'sunyou.choi@stpaulclark.com' WHERE full_name = 'Sunyou Choi';
UPDATE students SET email = 'timothyjeff.dayrit@stpaulclark.com' WHERE full_name = 'Timothy Jefferson Dayrit';
UPDATE students SET email = 'benjamin.garland@stpaulclark.com' WHERE full_name = 'Benjamin Jake Osabel Garland';
UPDATE students SET email = 'hyunyoung.jeong@stpaulclark.com' WHERE full_name = 'Hyunyoung Jeong';
UPDATE students SET email = 'ryukeon.kang@stpaulclark.com' WHERE full_name = 'Ryukeon Kang';
UPDATE students SET email = 'gaon.kim@stpaulclark.com' WHERE full_name = 'Ga-on Kim';
UPDATE students SET email = 'hyeyun.kim@stpaulclark.com' WHERE full_name = 'Hyeyun Kim';
UPDATE students SET email = 'kyuri.kim@stpaulclark.com' WHERE full_name = 'Kyuri Kim';
UPDATE students SET email = 'taegeon.kim@stpaulclark.com' WHERE full_name = 'Taegeon Kim';
UPDATE students SET email = 'seunghu.kim@stpaulclark.com' WHERE full_name = 'Seunghu Kim';
UPDATE students SET email = 'lowell.kwon@stpaulclark.com' WHERE full_name = 'Sihyun Kwon';
UPDATE students SET email = 'halin.lee@stpaulclark.com' WHERE full_name = 'Halin Lee';
UPDATE students SET email = 'jeongmo.lee@stpaulclark.com' WHERE full_name = 'Jeongmo Lee';
UPDATE students SET email = 'ryan.lee@stpaulclark.com' WHERE full_name = 'Ryan Agustin Lee';
UPDATE students SET email = 'azral@stpaulclark.com' WHERE full_name = 'Azra Nez Gabrielle Perez Lumbu-an';
UPDATE students SET email = 'jayrielle.mirasol@stpaulclark.com' WHERE full_name = 'Jayrielle Miriam Mirasol';
UPDATE students SET email = 'jazlynne.ong@stpaulclark.com' WHERE full_name = 'Jazlynne Nina Ong';
UPDATE students SET email = 'leah.park@stpaulclark.com' WHERE full_name = 'Leah Park';
UPDATE students SET email = 'alexandra.saburdo@stpaulclark.com' WHERE full_name = 'Alexandra Saburdo';
UPDATE students SET email = 'seongyun.seo@stpaulclark.com' WHERE full_name = 'Seongyun Seo';
UPDATE students SET email = 'jonjacob.smith@stpaulclark.com' WHERE full_name = 'Jon Jacob Dayrit Smith';
UPDATE students SET email = 'gel.stanley@stpaulclark.com' WHERE full_name = 'Gel Emrie Pedrito Stanley';
UPDATE students SET email = 'aryanna.wegner@stpaulclark.com' WHERE full_name = 'Aryanna Destiny Portugaliza Wegner';
UPDATE students SET email = 'jaewoong.yoon@stpaulclark.com' WHERE full_name = 'Jaewoong Yoon';
UPDATE students SET email = 'jueun.lee@stpaulclark.com' WHERE full_name = 'Jueun Lee';
UPDATE students SET email = 'chloeliz.adarlo@stpaulclark.com' WHERE full_name = 'Chloe Liz Adarlo';
UPDATE students SET email = 'seoyoonchang@stpaulclark.com' WHERE full_name = 'Seoyoon Chang';
UPDATE students SET email = 'jiyoo.choi@stpaulclark.com' WHERE full_name = 'Jiyoo Choi';
UPDATE students SET email = 'rahee.jang@stpaulclark.com' WHERE full_name = 'Rahee Jang';
UPDATE students SET email = 'seokyung.joo@stpaulclark.com' WHERE full_name = 'Seokyung Joo';
UPDATE students SET email = 'minsung.kim@stpaulclark.com' WHERE full_name = 'Minsung Kim';
UPDATE students SET email = 'daeunlee@stpaulclark.com' WHERE full_name = 'Daeun Lee';
UPDATE students SET email = 'gyuri.lim@stpaulclark.com' WHERE full_name = 'Gyuri Lim';
UPDATE students SET email = 'hao-ming.wang@stpaulclark.com' WHERE full_name = 'Hao-Ming Wang';
UPDATE students SET email = 'jaein.ahn@stpaulclark.com' WHERE full_name = 'Jaein Ahn';
UPDATE students SET email = 'annie.altangerel@stpaulclark.com' WHERE full_name = 'Anir Altangerel';
UPDATE students SET email = 'jaehyun.choi@stpaulclark.com' WHERE full_name = 'Jaehyun Choi';
UPDATE students SET email = 'sophia.corpuz@stpaulclark.com' WHERE full_name = 'Sophia Juanita Noreve Corpuz';
UPDATE students SET email = 'nash.cruz@stpaulclark.com' WHERE full_name = 'John Ignacio Pamintuan Cruz';
UPDATE students SET email = 'timo.frey@stpaulclark.com' WHERE full_name = 'Timo Wendelin Frey';
UPDATE students SET email = 'taehoonha@stpaulclark.com' WHERE full_name = 'Taehoon Ha';
UPDATE students SET email = 'michael.hickey@stpaulclark.com' WHERE full_name = 'Michael Edward Hickey';
UPDATE students SET email = 'ju.hong@stpaulclark.com' WHERE full_name = 'Hyongju Hong';
UPDATE students SET email = 'shiyuhuang@stpaulclark.com' WHERE full_name = 'Shiyu Huang';
UPDATE students SET email = 'you-eun.kim@stpaulclark.com' WHERE full_name = 'Youeun Kim';
UPDATE students SET email = 'riwon.kim9@stpaulclark.com' WHERE full_name = 'Riwon Kim';
UPDATE students SET email = 'shinwook@stpaulclark.com' WHERE full_name = 'Shinwook Kim';
UPDATE students SET email = 'woojin@stpaulclark.com' WHERE full_name = 'Woojin Ko';
UPDATE students SET email = 'emily.kwon@stpaulclark.com' WHERE full_name = 'Sieun Kwon';
UPDATE students SET email = 'dayeon.lee@stpaulclark.com' WHERE full_name = 'Dayeon Lee';
UPDATE students SET email = 'seungwon.lee@stpaulclark.com' WHERE full_name = 'Seungwon Lee';
UPDATE students SET email = 'jonathan.lerio@stpaulclark.com' WHERE full_name = 'Jonathan Michael Lerio';
UPDATE students SET email = 'jhihyun.li@stpaulclark.com' WHERE full_name = 'Jhih-Yun Li';
UPDATE students SET email = 'jasmine.line@stpaulclark.com' WHERE full_name = 'Jasmine Kelly Line';
UPDATE students SET email = 'manuel.nablo@stpaulclark.com' WHERE full_name = 'Manuel Nablo Jr.';
UPDATE students SET email = 'subhin.oh@stpaulclark.com' WHERE full_name = 'Subhin Oh';
UPDATE students SET email = 'cyruz.papango@stpaulclark.com' WHERE full_name = 'Cyrus Dave Papango';
UPDATE students SET email = 'jooeun.park@stpaulclark.com' WHERE full_name = 'Jooeun Park';
UPDATE students SET email = 'seoyeon.park@stpaulclark.com' WHERE full_name = 'Seoyeon Park';
UPDATE students SET email = 'serin.park@stpaulclark.com' WHERE full_name = 'Serin Park';
UPDATE students SET email = 'jeongwoo.seo@stpaulclark.com' WHERE full_name = 'Jeongwoo Seo';
UPDATE students SET email = 'ayeong.son@stpaulclark.com' WHERE full_name = 'Ayeong Son';
UPDATE students SET email = 'ngochan.tran@stpaulclark.com' WHERE full_name = 'Ngoc Han Tran';
UPDATE students SET email = 'taewoong.yoon@stpaulclark.com' WHERE full_name = 'Taewoong Yoon';
UPDATE students SET email = 'seoyeong.yu@stpaulclark.com' WHERE full_name = 'Seoyeong Yu';
UPDATE students SET email = 'kendra.zaicek@stpaulclark.com' WHERE full_name = 'Kendra Jeanelle Zaicek';
UPDATE students SET email = 'phuoc.bui@stpaulclark.com' WHERE full_name = 'Phuoc Nhan Bui';
UPDATE students SET email = 'du.tommy@stpaulclark.com' WHERE full_name = 'Tommy Du';
UPDATE students SET email = 'seojinj@stpaulclark.com' WHERE full_name = 'Seojin Joug';
UPDATE students SET email = 'seojunj@stpaulclark.com' WHERE full_name = 'Seojun Joug';
UPDATE students SET email = 'yijoon@stpaulclark.com' WHERE full_name = 'Yijoon Kim';
UPDATE students SET email = 'dohee.kwon@stpaulclark.com' WHERE full_name = 'Dohee Kwon';
UPDATE students SET email = 'heeminkwon@stpaulclark.com' WHERE full_name = 'Heemin Kwon';
UPDATE students SET email = 'haon.lee@stpaulclark.com' WHERE full_name = 'Haon Lee';
UPDATE students SET email = 'naeun.lee@stpaulclark.com' WHERE full_name = 'Naeun Lee';
UPDATE students SET email = 'seungminlee@stpaulclark.com' WHERE full_name = 'Seungmin Lee';
UPDATE students SET email = 'czyrel.marzan@stpaulclark.com' WHERE full_name = 'Czyrel Marzan';
UPDATE students SET email = 'john.mirasol@stpaulclark.com' WHERE full_name = 'John Marcial Mirasol';
UPDATE students SET email = 'angelica.mustafa@stpaulclark.com' WHERE full_name = 'Precious Angelica Mustafa';
UPDATE students SET email = 'bat-ochir.odmandakh@stpaulclark.com' WHERE full_name = 'Bat-Ochir Odmandakh';
UPDATE students SET email = 'byeongjun.park@stpaulclark.com' WHERE full_name = 'Byeongjun Park';
UPDATE students SET email = 'gahyun.park@stpaulclark.com' WHERE full_name = 'Gahyun Park';
UPDATE students SET email = 'jiwon.park@stpaulclark.com' WHERE full_name = 'Jiwon Park';
UPDATE students SET email = 'yunseo.park@stpaulclark.com' WHERE full_name = 'Yunseo Park';
UPDATE students SET email = 'mara.sarinas@stpaulclark.com' WHERE full_name = 'Mara-Alexandria Cortes Sarinas';
UPDATE students SET email = 'yujun.an@stpaulclark.com' WHERE full_name = 'Yujun An';
UPDATE students SET email = 'kevin.chen@stpaulclark.com' WHERE full_name = 'Siyue Chen';
UPDATE students SET email = 'christiandavid@stpaulclark.com' WHERE full_name = 'Christian Dylan Quiambao David';
UPDATE students SET email = 'jiyeong@stpaulclark.com' WHERE full_name = 'Jiyeon Go';
UPDATE students SET email = 'bryanh@stpaulclark.com' WHERE full_name = 'Seungju Hong';
UPDATE students SET email = 'jun.kim@stpaulclark.com' WHERE full_name = 'Minjun Kim';
UPDATE students SET email = 'jessica.kwon@stpaulclark.com' WHERE full_name = 'Sion Kwon';
UPDATE students SET email = 'seanl@stpaulclark.com' WHERE full_name = 'Sean Lee';
UPDATE students SET email = 'soyeon@stpaulclark.com' WHERE full_name = 'Soyeon Lee';
UPDATE students SET email = 'seanp@stpaulclark.com' WHERE full_name = 'Sieon Park';
UPDATE students SET email = 'jinseop@stpaulclark.com' WHERE full_name = 'Jinseo Park';
UPDATE students SET email = 'jaehoon.sohn@stpaulclark.com' WHERE full_name = 'Jaehoon Sohn';
UPDATE students SET email = 'luigi.yapjoco@stpaulclark.com' WHERE full_name = 'Luigi Marco Yapjoco';
UPDATE students SET email = 'gia.nguyen@stpaulclark.com' WHERE full_name = 'Nguyen Gia Bao';

-- Add teachers
INSERT INTO teachers (name, email) VALUES ('Yna Kristina Dela Cruz', 'delacruz@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Alyanna Carlos', 'alyannac@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Beverly Carino', 'beverly.carino@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Crystal Layug', 'crystall@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Dennis Alimpolos', 'dennis.alimpolos@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Garrett Anderson', 'garrett.anderson@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Jeo Cruz', 'jeo.cruz@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Kristine Ann Pangan', 'kristineann.pangan@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Mariedelle Turla', 'mariedelle@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Meryl Joy T Alcayro', 'mj.alcayro@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Michael Barredo', 'michael.barredo@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Nicholas Smith', 'smith.nj@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Ryan Dloski', 'ryan.dloski@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Sebastian Maria Verdugo Pedrero', 'sebastian@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Stephen Ward', 'stephenw@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Syrha Faustino', 'syrha.faustino@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Vicky Jeong', 'vicky.jeong@stpaulclark.com');
INSERT INTO teachers (name, email) VALUES ('Yubo Chen', 'yubo.chen@stpaulclark.com');

-- Add principal account
INSERT INTO students (full_name, english_name, email, grade) VALUES ('Dennis Principal', 'Dennis', 'imdennisalimpolos@gmail.com', '12');